# -*- coding: utf-8 -*-
"""07_sentiment_by_categoryVF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PpL5TZOaOc2sID-LuQG1rCY1WECxuxc

# Sentiment Analysis by Product Category

This notebook explores how customer sentiment varies across product categories. We use the `sentiment_polarity` feature to identify trends, satisfaction levels, and potential issues by category group.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_parquet("/content/engineered_features.parquet")
print("Data loaded:", df.shape)

"""## Sentiment Distribution by Category Group"""

plt.figure(figsize=(12, 6))
sns.boxplot(y='category_group', x='sentiment_polarity', data=df, orient='h')
plt.title("Sentiment Polarity by Category Group")
plt.xlabel("Sentiment Polarity")
plt.ylabel("Category Group")
plt.tight_layout()
plt.show()

"""## Average Sentiment per Category"""

sentiment_summary = df.groupby('category_group')['sentiment_polarity'].agg(['mean', 'std', 'count']).sort_values('mean', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x=sentiment_summary.index, y=sentiment_summary['mean'], palette='coolwarm')
plt.title("Average Sentiment Polarity by Category Group")
plt.xticks(rotation=45)
plt.ylabel("Average Polarity")
plt.xlabel("Category Group")
plt.tight_layout()
plt.show()

"""## Sentiment Distribution Histogram"""

plt.figure(figsize=(10, 5))
sns.histplot(df['sentiment_polarity'], bins=50, kde=True, color='purple')
plt.title("Overall Sentiment Polarity Distribution")
plt.xlabel("Polarity Score")
plt.ylabel("Frequency")
plt.show()

"""## Export Summary Table"""

sentiment_summary.to_csv("sentiment_by_category_summary.csv")