# -*- coding: utf-8 -*-
"""ydata-profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12i4Lc82rx_P20x4YbJ8_RKh6XxYuv9o1
"""

# YData Profiling
!pip install ydata-profiling --quiet

#
import pandas as pd
from ydata_profiling import ProfileReport
from google.colab import files

# .parquet
uploaded = files.upload()

# DataFrame
df = pd.read_parquet("engineered_features.parquet")

#
textual_columns = [
    "reviews.text", "reviews.title", "reviews.username",
    "reviews.sourceURLs", "label_text", "clean_text",
    "purchase_status", "recommend_status", "sentiment_category",
    "brand", "categories", "manufacturer", "manufacturerNumber",
    "name", "main_category", "category_group", "keys", "upc"
]
df_clean = df.drop(columns=textual_columns, errors="ignore")

#
profile = ProfileReport(
    df_clean,
    title="Engineered Features Profiling Report",
    explorative=True
)

#
profile.to_notebook_iframe()

#
profile.to_file("profiling_report.html")